=== kshitij-kamdi/HTML-practicals/practical_5/students.dtd
<!ELEMENT students (student+)>
<!ELEMENT student (name, course, email)>
<!ATTLIST student student_id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT course (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== kshitij-kamdi/HTML-practicals/practical_5/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="students.xsl"?>
<!DOCTYPE students SYSTEM "students.dtd">
<students>
    <student student_id="S101">
        <name>Kshitij Kamdi</name>
        <course>Computer Science</course>
        <email>kshitij@Kamdi.com</email>
    </student>
    <student student_id="S102">
        <name>Ojas Rahate</name>
        <course>Mechanical Engineering</course>
        <email>Ojas@Rahate.com</email>
    </student>
    <student student_id="S103">
        <name>Sanket Dhobale</name>
        <course>Business Administration</course>
        <email>Sanket@Dhobale.com</email>
    </student>
</students>
